
from Analysis_lib import*
from Generate_samples import*
from time import time

#Loading samples generated by Generate_samples.py file
cwd='Results\\24-Aug-2022-(20.48.26.584363)\\'
excel_file=cwd+'nsamples=100000.0_nsubspace=24.0alpha=2.1loss=0.00ncoh=3.999892_displaced_samples_cov.csv'
TA=log_data(excel_file)[:10000]
print(TA[:10])
#Loading the graph from TaceAs problem

#Using the adjacency matrix reduced to the first 10 modes to be consistent with the GBS simulation
Adj =data.TaceAs().adj

#Retrieving the potential values for the adjacency matrix
weights=make_potential_vect()

# Histogram of the number of photons per sample
a,nmax=plot_histogram(TA,plot=True)
print(a)

# #Remove the non-zero clicks event and the collision events
cleaned_samples,ncollision=clean_samples(TA,nmax)
print(len(cleaned_samples))
print(ncollision)

# # Histogram of the number of photons per sample
# a,nmax2=plot_histogram(cleaned_samples,plot=False)
# print(a)


#Find the maximum clique with classical algorithm

cwd='big\\big_tau1.1_.csv'
BIG=log_data(cwd)
clique_max,clique_weight=find_max_clique(BIG,weights,networkx_conv=False)
print('clique_max',clique_max)
print('clique_weight',clique_weight)


# plot_success_rate_vs_niter(cleaned_GBS_samples=cleaned_samples,Adj=BIG,weights=weights,niter=30)
plot_histogram_clique_values(cleaned_GBS_samples=cleaned_samples,nmax=nmax,Adj=Adj,weights=weights,plot=True)




